<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname(dirname($vendorDir));

return array(
    'OwnerRez\\Api\\Resources\\' => array($vendorDir . '/ownerrez/orez-api/src/resources'),
    'OwnerRez\\Api\\Glue\\' => array($vendorDir . '/ownerrez/orez-api/src/glue'),
    'OwnerRez\\Api\\' => array($vendorDir . '/ownerrez/orez-api/src'),
);
