<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit292e44f67457e09063067003d91d2dc6
{
    public static $prefixLengthsPsr4 = array (
        'O' => 
        array (
            'OwnerRez\\Api\\Resources\\' => 23,
            'OwnerRez\\Api\\Glue\\' => 18,
            'OwnerRez\\Api\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'OwnerRez\\Api\\Resources\\' => 
        array (
            0 => __DIR__ . '/..' . '/ownerrez/orez-api/src/resources',
        ),
        'OwnerRez\\Api\\Glue\\' => 
        array (
            0 => __DIR__ . '/..' . '/ownerrez/orez-api/src/glue',
        ),
        'OwnerRez\\Api\\' => 
        array (
            0 => __DIR__ . '/..' . '/ownerrez/orez-api/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit292e44f67457e09063067003d91d2dc6::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit292e44f67457e09063067003d91d2dc6::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit292e44f67457e09063067003d91d2dc6::$classMap;

        }, null, ClassLoader::class);
    }
}
